name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add your external Tap
        run: brew tap NarekMosisian/mac-storage-manager

      - name: Update Homebrew
        run: brew update || true

      - name: Install formula from your Tap
        run: brew install --build-from-source mac-storage-manager

      - name: Run tests
        run: |
          brew test mac-storage-manager
          brew audit --strict mac-storage-manager

  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Homebrew on Linux
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> $HOME/.profile
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

      - name: Install zsh
        run: |
          sudo apt-get update
          sudo apt-get install -y zsh

      - name: Check zsh availability
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          echo "PATH: $PATH"
          which zsh
          zsh --version

      - name: Add your external Tap
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew tap NarekMosisian/mac-storage-manager

      - name: Update Homebrew and run doctor
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew update || true
          brew doctor || true

      - name: Install dependencies
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install jq newt

      - name: Uninstall previous version (if any)
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew uninstall mac-storage-manager || true

      - name: Build and install formula from source
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install --build-from-source ./Formula/mac-storage-manager.rb

      - name: Run tests
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew test mac-storage-manager
          brew audit --strict mac-storage-manager