name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-test:
    runs-on: macos-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Install Homebrew
      - name: Install Homebrew
        run: |
          if ! command -v brew >/dev/null; then
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
            echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> $HOME/.zprofile
            eval "$(/opt/homebrew/bin/brew shellenv)"
          fi

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          brew install jq newt bats-core

      # 4. Run unit tests with Bats
      - name: Run Tests
        run: bats tests/

      # 5. Upload logs if tests fail
      - name: Upload logs
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: application_size_checker-log
          path: application_size_checker.log
