name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add your external Tap
        run: brew tap NarekMosisian/mac-storage-manager

      - name: Update Homebrew
        run: brew update || true

      - name: Install formula from your Tap
        run: brew install --build-from-source mac-storage-manager

      - name: Run tests
        run: |
          brew test mac-storage-manager
          brew audit --strict mac-storage-manager

  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Homebrew on Linux
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> $HOME/.profile
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

      - name: Add your external Tap
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew tap NarekMosisian/mac-storage-manager

      - name: Update Homebrew
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew update || true

      - name: Install formula from your Tap
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install --build-from-source mac-storage-manager

      - name: Run tests
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew test mac-storage-manager
          brew audit --strict mac-storage-manager
